### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by cosmarvv** [atais/angular-eonasdan-datetimepicker#1]
Hi, this is working, but how can change date format, use seconds and assign an init datetime.
I want to do something like this:

defaultDate: moment(dateNow).hours(0).minutes(0).seconds(0).milliseconds(0),
format: "MM/DD/YYYY HH:mm:ss",
locale: 'es',

Thanks

**Comment by atais** [comment]
use the options parameter providing json input.
did you check out the plunker demo?

**Comment by cosmarvv** [comment]
Thanks, your DateTimePicker really works great!!
5 stars

**Comment by TinoPham** [comment]
It work great!

**Comment by David91vlc** [comment]
@cosmarvv How to set locale in options? I don't understand. I tpye locale es but not works

Regards
