### ISSUE TITLE
Open on input focus

### ISSUE THREAD

**Issue by hdn8** [atais/angular-eonasdan-datetimepicker#10]
Is this possible?  Some way to access the show methods would work, adding a click event and then firing the show() method, such as:  https://github.com/Eonasdan/bootstrap-datetimepicker/issues/704

**Comment by atais** [comment]
There is an answer in the issue you have mentioned!

use `allowInputToggle: true` option

**Comment by hdn8** [comment]
Excellent!  I didnt find that in the options, thanks.
