### ISSUE TITLE
Set Default Hour

### ISSUE THREAD

**Issue by oracleruiz** [atais/angular-eonasdan-datetimepicker#11]
Hi, I finished here because is the only date time picket that worked for me and that I like. But I was looking how to set a default hour to 00:00. Does it is supported? I did not found anything on documentation.

**Comment by atais** [comment]
First, this is only wrapper. If you are looking for options of the lib itself, ask here: https://github.com/Eonasdan/bootstrap-datetimepicker

Still, I do not know any option like this either, but you can use `moment` to change the date as you like:

``` javascript
moment().startOf('day')
```
