### ISSUE TITLE
Change watch for options to compare object (objectEquality == true)

### ISSUE THREAD

**Issue by taraskravec** [atais/angular-eonasdan-datetimepicker#13]
Hi, how in simple way change min/max date for two connected date pickers?
Only by directly assign options with min/max date using onChange function?

**Comment by atais** [comment]
Sorry I do not understand your question. Follow this example: http://plnkr.co/ZSjN8f

**Comment by taraskravec** [comment]
If write instead of:

```
 vm.update = function (dateFrom, dateTo) {
                vm.optionsFrom = {format: 'DD.MM.YYYY', maxDate: dateTo};
                vm.optionsTo = {format: 'DD.MM.YYYY', minDate: dateFrom};
            };
```

This one:

```
vm.optionsFrom = {......};
vm.optionsTo = {......};
......
 vm.update = function (dateFrom, dateTo) {
                vm.optionsFrom.maxDate = dateTo;
                vm.optionsTo.minDate = dateFrom;
            };
```

It will not work, because in this case optionsFrom object does not changed.

**Comment by atais** [comment]
Ah alright I understand now.

You referred to the angular docs: https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch `[objectEquality]`

I am wondering if the options object can get big enough to cause performance issues... Hopefully not 😄  I will add this function soon.

**Comment by atais** [comment]
Check out the new version.
Also updated the plunker: http://plnkr.co/edit/ZSjN8f

**Comment by taraskravec** [comment]
thanks
