### ISSUE TITLE
NgModel not properly synced/watched when using datetimepicker directive on input field 

### ISSUE THREAD

**Issue by anx-ckreuzberger** [atais/angular-eonasdan-datetimepicker#14]
Documentation says:
Simply add datetimepicker tag and add the ng-model (required) attribute. Currently the datetimepicker tag can be added on either input-group or the input element.

Apparently using a HTML5 input field and having ng-model aswell as datetimepicker directive on it will not work.

```HTML
                  <div class="input-group" >
                        <input type="text" class="form-control" datetimepicker
                         ng-model="vm.date" options="vm.options"/>
                         
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
```

```JavaScript
    angular.module('plunker', ['ae-datetimepicker'])
        .controller('controller', ["$timeout", function ($timeout) {
            var vm = this;

            $timeout(function() { // simulating a REST API Call that takes 500 ms
                vm.date = moment('2015-11-20T22:10:50Z');
            }, 500);
            
            vm.options = {format: 'YYYY/MM/DD HH:mm', showClear: true};
        }]);
```
However, setting ``vm.date = moment('2015-11-20T22:10:50Z');`` without a $timeout (which simulates a REST API call for me) will work fine.

The very same code also works fine when using the directive on the input-group:
```HTML
                    <div class="input-group"  datetimepicker
                         ng-model="vm.date" options="vm.options" >
                        <input type="text" class="form-control"/>
                         
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
```

See this plunkr: http://plnkr.co/edit/BNBcajgd6gD9bNksm4TM?p=preview

Hope this helps.

**Comment by atais** [comment]
I started investigating it and it is worse than I thought. I will need some more time to fix this one.

**Comment by akamarvin** [comment]
I agree with the issue reporter, when for instance you have another version of the same date field (so same model ) for the purpose of displaying a "summary" tab in a big multi-tab form , then that second one does not listen/sync with the change in the model from the other. So generally speaking, change to the model which may come from somewhere else than the current ae-DTP field are just not observed.  I was struggling to find a fix but for now I just resorted to some hack on my detailViewController to handle the refreshes, case by case (dirty). 
Otherwise, thank you for the great contrib.

**Comment by atais** [comment]
@anx-ckreuzberger OK I think I have solved the reported problem in `0.3.8`. Please check the update. I have updated the main plunker with both options: http://plnkr.co/edit/n8L8UZ?p=preview 

@Tamadadoo I am not sure, but possibly the update also solves your problem. If you can, update the library in your project and please report back.

**Comment by akamarvin** [comment]
Indeed the revised $render and onchange did the trick !  And also allowed for a proper management of required inputs, when they are emptied. Many thanks. All for the better.  
Out of curiosity, what did the deep watch of the options resolved ? what was the issue ? (the commit before)

**Comment by atais** [comment]
@Tamadadoo #13
