### ISSUE TITLE
Date not set on first open of the picker

### ISSUE THREAD

**Issue by reymonreyes** [atais/angular-eonasdan-datetimepicker#16]
Hi,

I'm experiencing a weird problem on the picker. This is what happens.
When datetimepicker is show for the first time it shows the current date.
![screenshot_1](https://cloud.githubusercontent.com/assets/476682/20926623/4d14b736-bbf8-11e6-8932-8123273b8e5a.jpg)
Then after opening it again it shows the correct date.
![screenshot_31](https://cloud.githubusercontent.com/assets/476682/20926642/718b7276-bbf8-11e6-9e8d-fad2b1ed8382.jpg)

I've tried setting the defaultDate option but it's still not working.
Looking forward to your response.

Thank you.

**Comment by atais** [comment]
can you reproduce with plunker?

**Comment by sjanofsky** [comment]
I'm experiencing the same issue... the ng-model is 

ng-model="student.DateOfBirth"

student is derived from this

<tr ng-repeat="student in students">

would this cause an issue?

I'm also not using the "controller as" methodology, would this cause an issue?

**Comment by atais** [comment]
simply fork the plunker ( http://plnkr.co/n8L8UZ ) and reproduce your issue

**Comment by sjanofsky** [comment]
It seems to be an issue with the original bootstrap-datetimepicker.js... at line 869 it shows the following:

//viewDate = date.clone(); // TODO this doesn't work right on first use

after uncommenting this line it works fine.

**Comment by atais** [comment]
which version of the date time picker you are using?

**Comment by atais** [comment]
new version is out + no answer
