### ISSUE TITLE
Does not set the value at all

### ISSUE THREAD

**Issue by gbluv** [atais/angular-eonasdan-datetimepicker#17]
I did setup exactly the same way as your plunker with the only difference that I use scope instead of controller as. Your plugin picks up the properties that way but value does not change. I've set up watcher on the model and it does not see the change in the value even though control shows and you can pick and choose date and that sets in to input box.

**Comment by atais** [comment]
can you fork the plunker and apply your changes?

**Comment by atais** [comment]
no response
