### ISSUE TITLE
form is loaded in $dirty state when used with moment object

### ISSUE THREAD

**Issue by yasar** [atais/angular-eonasdan-datetimepicker#19]
Hello,

Here is the plunker forked from one of the example provided here:
[http://plnkr.co/edit/YcPQNstLRsFxND4r3a7Z](http://plnkr.co/edit/YcPQNstLRsFxND4r3a7Z)

I added a line showing the dirty state of the form at the very bottom.

This is a serious issue for me. Is this something to your knowledge? any workaround or fix for this?
Thank you.

**Comment by atais** [comment]
Hi.

I admit it can be somehow an undesirable 'feature', but to be honest, I did not encounter this problem before. I have done a fast check and from what I see, even if the date is not set the form gets instantly `dirty`.

If you need a walkaround... I would simpy add this to your controller. 
```javascript
$timeout(function() {
  $scope.dateForm.$setPristine();
});
```

It works with a plunker: [http://plnkr.co/edit/L1HIMU](http://plnkr.co/edit/L1HIMU)

But to truly address this problem I would need to first find what causes the `dirty` state. Especially, if the problem lays in the wrapper or in the library.

At the moment I am not sure if I will have time to patch this (or find the source of an issue). Any PRs are welcome :smile:

**Comment by shustariov-andrey** [comment]
Problem lays within this line: https://github.com/atais/angular-eonasdan-datetimepicker/blob/master/dist/angular-eonasdan-datetimepicker.js#L29. When setting ngModel's view value, it becomes $dirty

**Comment by atais** [comment]
Thanks @shustariov-andrey !

But well... it is a core line of this wrapper.

I can see there is a walkaround, fe. http://stackoverflow.com/questions/28242788/how-to-reset-custom-input-directive-and-its-parent-form-to-pristine but it seems quite dirty to me.

I would appreciate any ideas.

**Comment by shustariov-andrey** [comment]
How about

```
if (ngModel.$viewValue === null) {
   ngModel.$setViewValue(null);
}
```
?

I mean, undefined value should not make model dirty at the first place

**Comment by atais** [comment]
I should start putting comments in that code :cry: 

the reason i check for ` !ngModel.$viewValue` instead of `ngModel.$viewValue === null` is that if you pass `undefined` or `false` to `ng-model` it would pass this value to the `datetimepicker`.

And actually `eonasdan-datetimepicker` does not like that and it causes console errors. The only value it accept is `moment` or `null` (I think `Date` was good too). 

I have actually done the above in previous version :wink: 


---------

What is more I think that it is not that `ngModel.$setViewValue(null);` causes `$dirty` state, but `ngModel.$setViewValue(moment(ngModel.$viewValue));` in general ?

And this is basically linking the model to date time picker.

**Comment by shustariov-andrey** [comment]
Ok, need to debug it deeper in this case...

**Comment by shustariov-andrey** [comment]
ok, here what works fine for me now:

```
            if (!_.isUndefined(ngModel.$viewValue) && !moment.isMoment(ngModel.$viewValue)) {
                ngModel.$setViewValue(moment(ngModel.$viewValue));
            }
            if (moment.isMoment(ngModel.$viewValue)) {
                dpElement.data('DateTimePicker').date(ngModel.$viewValue);
            }
```

**Comment by atais** [comment]
@shustariov-andrey would you fork the repo and make a PR?

I will test it and we can make a new version :+1: ?

**Comment by shustariov-andrey** [comment]
ok, will do

**Comment by atais** [comment]
Great! #21 fixed it. 

Enjoy `0.3.9` available on bower & npm :smile: !
