### ISSUE TITLE
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format

### ISSUE THREAD

**Issue by matt-senseye** [atais/angular-eonasdan-datetimepicker#23]
I am seeing the following warning in the console:

`Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Fri Feb 03 2012 00:00:00 GMT+0000 (GMT), _f: undefined, _strict: undefined, _locale: [object Object]`

From what I can tell, this is caused by this line: https://github.com/atais/angular-eonasdan-datetimepicker/blob/master/dist/angular-eonasdan-datetimepicker.js#L35

It appears that the value of `ngModel.$viewValue` is a string in the following format, and moment are deprecating the creation of moment objects using strings that are not in ISO format (as described in [the moment.js documentation](https://momentjs.com/guides/#/warnings/js-date/)):

`Fri Feb 03 2012 00:00:00 GMT+0000 (GMT)`

I have tried setting the value in my bound $scope property to be a moment object and a Javascript date object, but in either case it appears to get converted to a string somewhere along the line. I wonder if it is due to the difference between $modelValue and $viewValue but unfortunately I'm not sure how this works in enough detail.

Any help would be greatly appreciated :)

**Comment by atais** [comment]
To be honest, I don't work on angular projects anymore.

Fortunately, this wrapper is quite a mature project and it does not need much attention from my side :-)

I am aware of this warning though....
If you are really annoyed by its presence, you need to debug those lines:

https://github.com/atais/angular-eonasdan-datetimepicker/blob/master/dist/angular-eonasdan-datetimepicker.js#L34
https://github.com/atais/angular-eonasdan-datetimepicker/blob/master/dist/angular-eonasdan-datetimepicker.js#L48

and check
 - what kind of values are being set to the `$viewModel` value.
 - what is happening on the library side.
 
I have made some heavy tests with the latest version so if you want to try your chances I will be happy to accept a PR :+1: Good luck.

**Comment by matt-senseye** [comment]
Thanks for replying @atais. 

In the end I managed to work around it by forcing my date into ISO format before passing it in, using moment().toISOString(). That seems to eliminate the warning.
