### ISSUE TITLE
Support for jQuery 3 in dependencies

### ISSUE THREAD

**Issue by vladimirjegorov** [atais/angular-eonasdan-datetimepicker#25]
Hi,
We are using jQuery 3 in our project. But when resolving dependencies, NPM complains that angular-eonasdan-datetimepicker depends on jquery ~2. Can the dependency be changed to ">=2" instead? I currently see no problem. Or is there any? 
Thanks in advance :)

**Comment by atais** [comment]
Can't be, because the library does not support jQuery 3.

**Comment by vladimirjegorov** [comment]
Well, currently using jQuery 3 with eodasan picker in the project with Your angular wrapper, and the picker behaves as expected. In Eonasdan picker, actually, they use jQuery ">=1.8.3" which, as I understand would allow jQ v3. Or am I missing something?

> Can't be, because the library does not support jQuery 3.

Which library are you talking about? the picker or the wrapper? :)

**Comment by atais** [comment]
Picker.

https://github.com/Eonasdan/bootstrap-datetimepicker/issues/1751
