### ISSUE TITLE
How to configure global datetimepicker options like in diosney version

### ISSUE THREAD

**Issue by danielcastilho** [atais/angular-eonasdan-datetimepicker#27]
in diosney version existis a possibility of this code:
.module('app', [
				'datetimepicker'
			])
			.config([
				'datetimepickerProvider',
				function (datetimepickerProvider) {
					datetimepickerProvider.setOptions({
						locale: 'en'
					});
				}
			]);

**Comment by danielcastilho** [comment]
This should be a new Pull Request?

**Comment by atais** [comment]
what?
this was done since version 1.
