### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by fred87lim** [atais/angular-eonasdan-datetimepicker#30]
Hi. I was trying to add the datetimepicker into my webpage, and though the UI shown up fine but upon loading the webpage I see the following error:

`angular.js:14525 TypeError: Cannot read property 'length' of undefined
    at Function.map (jquery-1.10.2.js:789)
    at angular-eonasdan-datetimepicker.js:22
    at Scope.$digest (angular.js:17999)
    at Scope.$apply (angular.js:18269)
    at bootstrapApply (angular.js:1917)
    at Object.invoke (angular.js:5003)
    at doBootstrap (angular.js:1915)
    at bootstrap (angular.js:1935)
    at angularInit (angular.js:1820)
    at HTMLDocument.<anonymous> (angular.js:33367)` 

How to resolve this issue?

[Update] 
Sorry that I forgot to write my html code here. I have followed the given example. I have attached the code snippet here. Don't know why if I paste the code here it is not showing up. 
[code.txt](https://github.com/atais/angular-eonasdan-datetimepicker/files/1169466/code.txt)

I have included the javascript and declared the directive in my angular. The UI is showing up fine but when I inspect the page the error mentioned showed up.

**Comment by atais** [comment]
you messed up something. but I do not know what because you did not provide your example.
follow the given examples.

**Comment by atais** [comment]
sorry its impossible to help you
