### ISSUE TITLE
Setting date-only value from controller makes datetimepicker to display one day before

### ISSUE THREAD

**Issue by tahaerden** [atais/angular-eonasdan-datetimepicker#38]
Here is the input:
`<input datetimepicker options="{format: 'YYYY-MM-DD'}" type="text" class="form-control" name="myDate" ng-model="myDate" required>`

And I set the date in controller:
`$scope.myDate = '2019-03-25'`

Now the directive shows the date as '2019-03-**24**'.  I think even if there is no time selection (because of the format) it still takes it into consideration as 00:00 and because of UTC timezone it shows a day before.

I could only get over this by setting the date with some dummy time value:
`$scope.myDate = '2019-03-25T14:00:00'`

Is there a better solution? I don't want to change the date format in my controller because it actually comes from an API response.

**Comment by atais** [comment]
try creating a date object of the date you want not a simple string

**Comment by tahaerden** [comment]
> try creating a date object of the date you want not a simple string

Thanks for the quick response @atais ,

When I create a date object with the string date coming from API, something like this:
`$scope.myDate = new Date('2019-03-25')`

It works correctly because now myDate is: 
`Mon Mar 25 2019 03:00:00 GMT+0300 (GMT+03:00)`
Does that mean somewhere in UTC minus timezone (such as ADT UTC-3) it will again shown one day before? Or are we safe now?

In addition, do you think it is a good idea to add an option (i.e. dateOnly:true) for such data without time? In this case it automatically creates new Date object from given string date?

Thanks in advance.

**Comment by atais** [comment]
You are facing a standard problem with TimeZones.

> Or are we safe now?

You are safe, but read about the issue and try to understand it. 

>  dateOnly:true

Does not matter. It won't help with timezones either.
