### ISSUE TITLE
Impossible to select dates because day replaces month

### ISSUE THREAD

**Issue by jnm2** [atais/angular-eonasdan-datetimepicker#6]
Bug demo: https://plnkr.co/M0nMTy

To see the bug, select one of the first twelve days of any month, say 08/02/2016, and see that the picker changes it to 02/20/2016 (the 20th is today's date at the time of writing). Select 08/03/2016 and it changes to 03/20/2016.

The main difference is that the `datetimepicker` and `ng-model` attributes are on the input element rather than the containing div, which [according to your readme](https://github.com/atais/angular-eonasdan-datetimepicker#directive-usage) is allowed.

Before I discovered that the placement of `datetimepicker` had an impact, I also discovered that it fixed the problem to change [this line](https://github.com/atais/angular-eonasdan-datetimepicker/blob/2cbc4439ac0b7ab2a1494b24b3a896a855239216/dist/angular-eonasdan-datetimepicker.js#L29) to `dpElement.data('DateTimePicker').date(ngModel.$viewValue.clone());`. I don't know the significance of that. Now that I know the placement of `datetimepicker` has an impact, it seems like there might be a deeper issue than `.clone()`.

**Comment by atais** [comment]
It has nothing to do with the wrapper.

Actually your `script.js` is simply broken.

``` javascript
var date = null;
return {
   get date() { return date == null ? null : moment(date); },
   set date(value) { date = value.valueOf(); }
};
```

if you follow the original example, replace the above with 

``` javascript
var vm = this;

vm.date = moment();
vm.options = {format: "YYYY/MM/DD HH:mm"};

vm.getTime = function () {
   alert('Selected time is:' + vm.date.format("YYYY/MM/DD HH:mm"))
};

vm.addTime = function (val, selector) {
   vm.date = moment(vm.date.add(val, selector));
};
```

everything works.

**Comment by jnm2** [comment]
@atais I need the getter and setter with a `Date`-typed backing field. That's not something I can work around.

**Comment by jnm2** [comment]
@atais I need the getter and setter with a Number-typed backing field. That's not something I can work around. I can keep both a moment object and a number but sooner or later they have to reconcile both directions and this problem happens.

The whole point of the script.js is to boil the issue down to the essentials. Getters and setters are a good viewmodel pattern and the setter is essential to do other work in my model.

**Comment by atais** [comment]
@jnm2 I have not used your way before.

Still, I do not really know what you are trying to achieve, but you bind your the `ng-model` of datetimepicker to `vm.date` and in controller you are not using `vm` object. So you simply do not bind the controller value to the datepicker value - and that is why the problem occurs.

**Comment by jnm2** [comment]
@atais I don't think that can be correct. The controller property is getting bound. Put `alert('x')` in the getter or setter to see it. Angular was designed so that getters and setters can be used this way.

Also, you can see what to expect from the code. The controller factory returns `{ get() date, set(value) date }` as the controller, then the ng-controller is `controller as vm`, so `vm.date` is definitely referring to the getter and setter we returned from the controller factory.

**Comment by atais** [comment]
Hm, you are right. As I told, I have not used this way before. I have tried putting a starting date and displaying it though, and got an [error](https://docs.angularjs.org/error/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22msg%22:%22fn:%20function%20%28%29%7Bvar%20b%3Dp%28a%29;if%28b!%3D%3Dr.$modelValue%26%26%28r.$modelValue%3D%3D%3Dr.$modelValue%7C%7Cb%3D%3D%3Db%29%29%7Br.$modelValue%3Dr.$$rawModelValue%3Db;z%3Dvoid%200;for%28var%20c%3Dr.$formatters,d%3Dc.length,e%3Db;d--;%29e%3Dc%5Bd%5D%28e%29;r.$viewValue!%3D%3De%26%26%28r.$$updateEmptyClasses%28e%29,r.$viewValue%3Dr.$$lastCommittedViewValue%3De,r.$render%28%29,%5Cnr.$$runValidators%28b,e,C%29%29%7Dreturn%20b%7D%22,%22newVal%22:%222016-08-29T15:17:44.518Z%22,%22oldVal%22:%222016-08-29T15:17:44.518Z%22%7D%5D,%5B%7B%22msg%22:%22fn:%20function%20%28%29%7Bvar%20b%3Dp%28a%29;if%28b!%3D%3Dr.$modelValue%26%26%28r.$modelValue%3D%3D%3Dr.$modelValue%7C%7Cb%3D%3D%3Db%29%29%7Br.$modelValue%3Dr.$$rawModelValue%3Db;z%3Dvoid%200;for%28var%20c%3Dr.$formatters,d%3Dc.length,e%3Db;d--;%29e%3Dc%5Bd%5D%28e%29;r.$viewValue!%3D%3De%26%26%28r.$$updateEmptyClasses%28e%29,r.$viewValue%3Dr.$$lastCommittedViewValue%3De,r.$render%28%29,%5Cnr.$$runValidators%28b,e,C%29%29%7Dreturn%20b%7D%22,%22newVal%22:%222016-08-29T15:17:44.518Z%22,%22oldVal%22:%222016-08-29T15:17:44.518Z%22%7D%5D,%5B%7B%22msg%22:%22fn:%20function%20%28%29%7Bvar%20b%3Dp%28a%29;if%28b!%3D%3Dr.$modelValue%26%26%28r.$modelValue%3D%3D%3Dr.$modelValue%7C%7Cb%3D%3D%3Db%29%29%7Br.$modelValue%3Dr.$$rawModelValue%3Db;z%3Dvoid%200;for%28var%20c%3Dr.$formatters,d%3Dc.length,e%3Db;d--;%29e%3Dc%5Bd%5D%28e%29;r.$viewValue!%3D%3De%26%26%28r.$$updateEmptyClasses%28e%29,r.$viewValue%3Dr.$$lastCommittedViewValue%3De,r.$render%28%29,%5Cnr.$$runValidators%28b,e,C%29%29%7Dreturn%20b%7D%22,%22newVal%22:%222016-08-29T15:17:44.518Z%22,%22oldVal%22:%222016-08-29T15:17:44.518Z%22%7D%5D,%5B%7B%22msg%22:%22fn:%20function%20%28%29%7Bvar%20b%3Dp%28a%29;if%28b!%3D%3Dr.$modelValue%26%26%28r.$modelValue%3D%3D%3Dr.$modelValue%7C%7Cb%3D%3D%3Db%29%29%7Br.$modelValue%3Dr.$$rawModelValue%3Db;z%3Dvoid%200;for%28var%20c%3Dr.$formatters,d%3Dc.length,e%3Db;d--;%29e%3Dc%5Bd%5D%28e%29;r.$viewValue!%3D%3De%26%26%28r.$$updateEmptyClasses%28e%29,r.$viewValue%3Dr.$$lastCommittedViewValue%3De,r.$render%28%29,%5Cnr.$$runValidators%28b,e,C%29%29%7Dreturn%20b%7D%22,%22newVal%22:%222016-08-29T15:17:44.518Z%22,%22oldVal%22:%222016-08-29T15:17:44.518Z%22%7D%5D,%5B%7B%22msg%22:%22fn:%20function%20%28%29%7Bvar%20b%3Dp%28a%29;if%28b!%3D%3Dr.$modelValue%26%26%28r.$modelValue%3D%3D%3Dr.$modelValue%7C%7Cb%3D%3D%3Db%29%29%7Br.$modelValue%3Dr.$$rawModelValue%3Db;z%3Dvoid%200;for%28var%20c%3Dr.$formatters,d%3Dc.length,e%3Db;d--;%29e%3Dc%5Bd%5D%28e%29;r.$viewValue!%3D%3De%26%26%28r.$$updateEmptyClasses%28e%29,r.$viewValue%3Dr.$$lastCommittedViewValue%3De,r.$render%28%29,%5Cnr.$$runValidators%28b,e,C%29%29%7Dreturn%20b%7D%22,%22newVal%22:%222016-08-29T15:17:44.518Z%22,%22oldVal%22:%222016-08-29T15:17:44.518Z%22%7D%5D%5D).

So I guess same thing can happen while setting the date, but to be honest I am clueless what is wrong and how to fix it.

I have found only this way:

``` javascript
return {
    get date() { return date == null ? null : date; },
    set date(value) { date = value; }
};
```

**Comment by jnm2** [comment]
Gotcha. I discovered the workaround I mentioned in my original post but I don't totally understand it either. I can submit a PR with the fix but I want to take time to figure out why the fix works and if it's the right fix.

**Comment by atais** [comment]
I mean I could see why this is happening, because you return new moment object each time and read its value, thus making the calendar to update this value to a moment and so on.

But I am not sure if this is more of a wrapper fault or your code :P

Its not  nice, but I think you should head more-less this way:

``` javascript
return {
    get date() { 
      if (moment.isMoment(date)){
        console.log('is date!');
        return date;
      } else if (date == null){
        console.log('is null!');
        return null;
      } else {
        console.log('is ohh!');
        return moment(date);
      }
    },
    set date(value) { date = value; }
};
```

**Comment by jnm2** [comment]
So here's why I need to convert to and from a number. The viewmodel doesn't actually store the date itself; it forwards the get and set to a `ViewportService.offset` property which must be a number and which scrolls a bunch of d3.js graphs. When you zoom in and out, `ViewportService.offset` also changes (so that the center of the zoom is always under the mouse cursor). That means `vm.date` changes, which means a new moment object has to be created from a mathematically calculated number.

**Comment by atais** [comment]
You could make a nice StackOverflow question out of it... but in the end you will need more than just a getter and a setter. Still I did not have a problem like that.

**Comment by atais** [comment]
Anyway, if you happen to find a way to fix it I would gladly accept the PR :+1:

**Comment by atais** [comment]
any conclusion :-)?

**Comment by jnm2** [comment]
Wow, I'm behind. I have a fix. Will follow up soon.

**Comment by atais** [comment]
There is a big change in updating of the `ng-model` in `0.3.8` so the issue would have to be retested.
