### ISSUE TITLE
Update min/max date dynamically

### ISSUE THREAD

**Issue by agenestar** [atais/angular-eonasdan-datetimepicker#7]
I know an issue is not a question, but I can't find any example 

Is it possible to update the min and max date dynamically?

**Comment by atais** [comment]
There is an example exactly like this...

**Comment by jnm2** [comment]
It's under https://github.com/atais/angular-eonasdan-datetimepicker#examples, and it's called "Example with two, linked datetimepickers."

**Comment by agenestar** [comment]
Sorry guys, this issue was meant to be created in another repository. I was comparing directives and I mixed it up.
