### ISSUE TITLE
current date change to maxDate if it is today

### ISSUE THREAD

**Issue by Maethorin** [atais/angular-eonasdan-datetimepicker#8]
I'm setting the ng-model of the datetimepicker to a date 4 days past and the maxDate to today. When I render the page, the current date show for less than a second and then it changes to maxDate. If I use anything different from today as maxDate, it keeps the correct current date. The problem is only when i set maxDate to today:

CONTROLLER:

```
    var finishDate = moment();
    var startDate = moment();
    startDate.subtract(4, 'days');

    $scope.interval = {
      start: startDate,
      finish: finishDate
    };

    var today = moment();
    $scope.startDateOptions = {
      format: 'DD/MM/YYYY',
      maxDate: today
    };
```

HTML:

```
  <div class="form-group">
    <div class="input-group" datetimepicker ng-model="interval.start" options="startDateOptions">
      <input type="text" class="form-control" />
      <span class="input-group-addon">
         <span class="input-icon">
           <i class="glyphicon glyphicon-calendar"></i>
         </span>
       </span>
     </div>
   </div>
```

How can I fix this? How can I have the maxDate set to today without change the current date?

TY!

**Comment by Maethorin** [comment]
srry dude, just after posting this I see that you code is really just a wrapper and could not be the cause of this problem... I'll post this at the component github

**Comment by atais** [comment]
I think that your problem is not in the wrapper nor in the lib. It is because of your code 

> the current date show for less than a second

you have the source of issue in front of you.

**Comment by Maethorin** [comment]
Nope... this was not the case... 

Reading the issues in the bootstrap-datepicker github, I found other ppl with the same problem and what they suggest to fix their problems work for me too... I needed to set `useCurrent` to `false` in the datepicker options... So.. it's a component issue and this is some workaround... 

Ty anyway
