### ISSUE TITLE
Two way ng-model binding not working

### ISSUE THREAD

**Issue by elaith9** [atais/angular-eonasdan-datetimepicker#9]
I can get value from ng-model but i cannot set it. Also if i change property inside options, it doesnt take effect. Any ideas what it might be? I literally copied example from your plunker.

PS: i found solution for ng-model not working, datetimepicker attribute was on wrong element, but i still canont change options "on fly". I also noticed if i put 120 into stepping it still lets me choose every hour instead of every second hour as it should.

**Comment by atais** [comment]
Without a plunker with the problem I am not able to help.
